require "spec"
require "../src/cargo_tracker"
require "../src/cargo_tracker/domain/shared/*"
require "../src/cargo_tracker/domain/model/cargo/*"
require "../src/cargo_tracker/domain/model/location/*"
